apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeenergymanagementsystem
spec:
  selector:
    matchLabels:
      app: homeenergymanagementsystem
  replicas: 1
  template:
    metadata:
      labels:
        app: homeenergymanagementsystem
    spec:
      containers:
        - name: homeenergymanagementsystem
          image: adouni/homeenergymanagementsystem:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
